name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: ['macos-latest']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: cleaning
      run: |
         # https://github.com/helkhalfi/dotfiles/runs/1691237811#step:3:2964
         rm -rf rm '/usr/local/bin/aws'

    - name: Run Installer
      run: |
         /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
         brew bundle install --no-upgrade --file Brewfile
        #./install