name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ 'macos-11.0']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Run Installer
      run: |
        #./install
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        brew bundle install --no-upgrade --file Brewfile
        brew cleanup

