name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ 'macos-11.0']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Run Installer
      run: |
        ./install